# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


variables:
  buildConfiguration: 'Release'

pool:
  vmImage:'macOS10.13'



steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'building'
- script: dotnet test Tests/Tests.csproj
  displayName: 'testing'

